{% set version = "2.4.0" %}

package:
  name: consensify
  version: 2.4.0

source:
  url: https://github.com/jlapaijmans/Consensify/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2b88cda2c6ad44b6fd749d86485d3f16418b189b9c8ff4d20dd19640792dac1e

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('consensify', max_pin="x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - zlib
    
test:
  commands:
    - consensify_c -h

about:
  home: https://github.com/jlapaijmans/Consensify
  license: GPL3
  license_file: LICENCE.txt
  summary: A method for generating a consensus pseudohaploid genome sequence
  about: Consensify is a method for generating a consensus pseudohaploid genome sequence with greatly reduced error rates compared to standard pseudohaploidisation. The method is described in full and tested in the associated publication (Barlow et al. 2018).
